# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170830_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to=b'media/'),
        ),
    ]
