# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170830_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
