# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 08:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_blog_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
    ]
